name: Continuous Test

on:
  push:
    branches:
      - 'main'
  pull_request: {}

jobs:
  test_cpu:
    workflows: ["Code Sanity Checks", "Commit Check Policy"]
    runs-on: ubuntu-latest
    environment: continuous_test
    container:
      image: docker.io/jcfaracco/dasf:cpu_ci
    steps:
      - uses: actions/checkout@v4
      - name: Run test cases
        run: |
          pytest tests/
  test_gpu:
    workflows: ["Code Sanity Checks", "Commit Check Policy"]
    runs-on: ubuntu-latest
    environment: continuous_test
    # Skip this test for PRs due to dangerous code submitted.
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.CLUSTER_SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.CLUSTER_SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.CLUSTER_ADDRESS }} >> ~/.ssh/known_hosts
      - name: Test SSH connection
        run: |
          ssh -T ${{ secrets.CLUSTER_USER }}@${{ secrets.CLUSTER_ADDRESS }} -p 8686 > /dev/null
      - name: Pull latest docker image
        run: |
          ssh ${{ secrets.CLUSTER_USER }}@${{ secrets.CLUSTER_ADDRESS }} -p 8686 "ssh ${{ secrets.CLUSTER_GPU_ID }} \"docker pull jcfaracco/dasf:gpu\""
      - name: Run test cases remotely
        run: |
          ssh ${{ secrets.CLUSTER_USER }}@${{ secrets.CLUSTER_ADDRESS }} -p 8686 "ssh ${{ secrets.CLUSTER_GPU_ID }} \"docker run --rm --gpus all jcfaracco/dasf:gpu sh -c 'pip3 install pytest parameterized pip --upgrade && rm -rf dasf-core && git clone https://github.com/discovery-unicamp/dasf-core.git && cd dasf-core/ && pip3 uninstall dasf -y && pip3 install . && pytest tests/ && cd -'\""
