name: Commit Check Policy

on:
  push:
  pull_request:
    branches: 'main'
  workflow_dispatch:

jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: commit-check/commit-check-action@v1
        with:
          # we don't need message conventions right now
          message: false
          branch: true
          author-name: true
          author-email: true
          # Disable right now because it is broken.
          # https://github.com/commit-check/commit-check/pull/141
          commit-signoff: false
          job-summary: true
