name: Code Sanity Checks

on:
  push:
    branches:
      - 'main'
  pull_request: {}

jobs:
  test_cpu:
    runs-on: ubuntu-latest
    environment: continuous_test
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip3 install isort flake8 interrogate
      - name: Check imports with isort
        run: |
          # Show the diffs for debugging
          isort -c --df dasf/
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 dasf/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 dasf/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Doc lint with interrogate
        run: |
          # We should have at least 80% of docs covered
          interrogate -vv -i --fail-under=15
